### ISSUE TITLE
是否可以考虑加上七牛云的自定义图片样式？

### ISSUE THREAD

**Issue by zhaojun1998** [jiwenxing/qimage-win#19]
七牛云的自定义图片样式是在原图片 `url` 后加上一串参数表示某个图片样式。

例如： 
* 原图片：`http://oycr9aq9z.bkt.clouddn.com/201801141517_46.png`
* 自定义样式图片：`http://oycr9aq9z.bkt.clouddn.com/201801141517_46.png?imageView2/0/interlace/1/q/75|watermark/2/text/anVuNi5uZXQ=/font/Y29uc29sYXM=/fontsize/600/fill/I0VGRFRg==/dissolve/100/gravity/Soust/dx/10/dy/10|imageslim`

问号后面就是七牛云的自定义图片处理接口。

是否可以考虑加一个配置项来支持这个功能呢？

**Comment by jiwenxing** [comment]
我平时没用到过自定义样式，你希望是什么样，加一个可选配置来配自定义样式，生成链接的时候把样式拼接到url后面？

**Comment by zhaojun1998** [comment]
嗯，是这个意思。

**Comment by zhaojun1998** [comment]
因为七牛的这个图片样式可以加水印，图片瘦身、裁剪等功能，挺好用的，所以我想也会其他有人需要这个配置吧。

**Comment by zhaojun1998** [comment]
好的，刚试过了，很 nice，感谢。
